concurrent = 2
check_interval = 0

[session_server]
  listen_address = "127.0.0.1:8093"
  session_timeout = 1800

[[runners]]
  name = "runner-1"
  limit = 2
  url = "<gitlab url>"
  token = "<project token>"
  executor = "docker"
  shell = "bash"
  [runners.docker]
    tls_verify = false
    image = "docker:git"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs:/certs:ro", "/cache:/cache", "/usr/local/bin/docker-credential-ecr-login:/usr/local/bin/docker-credential-ecr-login:ro"]
    shm_size = 0
    environment = ["DOCKER_AUTH_CONFIG={\"credsStore\":\"ecr-login\"}"]

